/**
 * AMENDMENT A10 — DEPTH TRANSLATION BY A STILL HOLDER AND A MOVING ANCHOR.
 *
 * ⛔⛔ THIS FILE REPLACES A6's VECTORS, AND THE REASON IS THE WHOLE POINT. A6 asked whether
 * two fingers were travelling TOGETHER, which is a question with no answer for a window at
 * the start of every gesture and again at every reversal — and the owner rejected the
 * result on the glass: *"I don't like the conflict generated by the control of depth
 * translation by two fingers."*
 *
 * ⭐⭐ A10 ASKS A QUESTION THAT IS ALWAYS ANSWERABLE: is the finger ON THE OBJECT still?
 * If it is, the other finger's vertical travel is depth. If it is not, the gesture is rule
 * 6 and the other finger is an anchor. ⛔ There is no window, no ratio and no tolerance, so
 * there is nothing to wait for and nothing to tune.
 *
 * ⭐ And it is the SPEC's own vocabulary: §1.1 says *"every 'delta position' in the spec
 * means MOVING; every 'no delta position' means STATIONARY."* The gate reads the hysteretic
 * motion state, not a speed invented here.
 *
 * ⭐⭐ `METHOD`, and the reason this file composes two real `MotionTracker`s rather than
 * passing literal states: *a composition is a thing to MEASURE, not an emergent property.*
 * The gate itself is trivial; what a hand judges is the gate ON TOP OF the motion state,
 * with a real finger's noise in it.
 *
 * ⭐ HEIGHT NEVER CHANGES is carried over from A5 and still asserted: the push direction is
 * perpendicular to gravity by construction, and gravity is the primary constraint here.
 *
 * ⭐⭐ **THE PUSH DIRECTION NOW COMES FROM `gravityFrame`, 2026-09-17**, where it used to come
 * from `depthPushDirection` — a second computation of the same flattening, which the product
 * never called (it reads `frame.depth`). ⛔ Deleting it made these vectors BETTER, not just
 * shorter: they now exercise the mapping the scene actually uses.
 */
import { gravityFrame } from "../src/input/gravity_frame";
import { describe, expect, it } from "vitest";
import {
  rollDragDeg,
  secondFingerDrive,
  depthLimits,
  depthTranslate,
} from "../src/input/depth_translate";
import { DEFAULT_CONFIG, CAMERA_NEAR_PLANE_M } from "../src/input/gestureConfig";
import { dot, length, normalize, scale, sub, type Vec3 } from "../src/core/vec";
import { mmToPx } from "../src/core/units";

const DOWN: Vec3 = [0, -1, 0];
const CAM: Vec3 = [0, 0.8, -1.2];
const VIEW: Vec3 = normalize([0, -0.5, 1])!;
const OBJ: Vec3 = [0.15, 0.1, 0.1];
const { minM, maxM } = depthLimits(DEFAULT_CONFIG);
const PER_PX = 0.002; // rule 6's computed factor, at some camera distance

const push = gravityFrame(VIEW, DOWN)!.depth!;
const depthOf = (p: Vec3) => dot(sub(p, CAM), push);
/** ⭐ +1: this fixture's camera looks DOWN on the scene, so "away" rises on screen. */
const AWAY = Math.sign(dot(VIEW, DOWN));
const move = (dyPx: number, gain = 1, obj: Vec3 = OBJ) =>
  depthTranslate(CAM, obj, push, AWAY, dyPx, PER_PX, gain, minM, maxM);

// ══════════════════════════════════════════════════════════════════════════════
// ⭐⭐ THE GATE, COMPOSED WITH THE REAL MOTION STATE
// ══════════════════════════════════════════════════════════════════════════════

// ⚠ The `Finger` harness went with `A10`'s gate suite (2026-09-17): it drove two
// `MotionTracker`s with MEASURED jitter so the gate could be exercised against §1.1's real
// hysteresis. ⛔ Nothing left in this file needs two fingers simulated — `secondFingerDrive`
// takes motion STATES now, not samples — and a harness nothing uses is the next thing to rot.
// ⭐ `tests/motion_flick.test.ts` still drives trackers with the same noise, if one is needed.



// ⛔⛔⛔ **`A10`'s GATE SUITE WAS DELETED HERE — 2026-09-17, WITH THE GATE.**
//
// ⭐ It was one of the most instructive suites in the project: the gate read §1.1's
// HYSTERETIC states rather than speeds, and a vector compared it against the naive
// *both-fingers-moving* test to show that a common vertical drag reads DEPTH for twenty
// samples under the naive rule and `IDLE` under this one. ⛔ Its subject is gone: the owner
// wants both fingers integrated simultaneously, so there is nothing to discriminate.
//
// ⚠ The LESSON survives where it can still be acted on — `depth_translate.ts` carries the
// note about what the partition bought, and `queue_notes/IN8.md` holds the six models. ⭐ A
// vector whose subject cannot occur is not a safety net; these certified a function that no
// longer exists.

describe("⭐⭐ HEIGHT NEVER CHANGES — gravity is the primary constraint", () => {
  it("at every camera elevation", () => {
    for (const tilt of [0.1, 0.5, 1.5, 4]) {
      const view = normalize([0, -tilt, 1])!;
      const out = depthTranslate(CAM, OBJ, gravityFrame(view, DOWN)!.depth!, Math.sign(dot(view, DOWN)), mmToPx(-20), PER_PX, 1, minM, maxM);
      expect(out[1], `tilt ${tilt}`).toBeCloseTo(OBJ[1], 12);
    }
  });

  it("⛔ and the across-view offset is untouched too — only the depth moves", () => {
    const across = (p: Vec3) => {
      const r = sub(p, CAM);
      return sub(sub(r, scale(push, dot(r, push))), scale(DOWN, dot(r, DOWN)));
    };
    expect(length(sub(across(move(mmToPx(-30))), across(OBJ)))).toBeCloseTo(0, 12);
  });
});

describe("the sense and the size of the motion", () => {
  it("⚠ fingers UP push the object AWAY — it sits higher on screen when further off", () => {
    expect(depthOf(move(mmToPx(-20)))).toBeGreaterThan(depthOf(OBJ));
  });

  it("fingers DOWN bring it closer", () => {
    expect(depthOf(move(mmToPx(20)))).toBeLessThan(depthOf(OBJ));
  });

  it("⭐⭐ moves as far as RULE 6 would for the same travel — gain 1 means CONSISTENT, not tracking", () => {
    // 30 mm of finger at this camera factor: the same world distance a screen-plane drag
    // would cover, just pointed into the scene instead of across it.
    const travelPx = mmToPx(30);
    expect(depthOf(move(-travelPx)) - depthOf(OBJ)).toBeCloseTo(travelPx * PER_PX, 9);
  });

  it("is linear in the travel, and in the gain", () => {
    expect(depthOf(move(-mmToPx(30))) - depthOf(OBJ)).toBeCloseTo(
      3 * (depthOf(move(-mmToPx(10))) - depthOf(OBJ)),
      9,
    );
    expect(depthOf(move(-mmToPx(10), 2)) - depthOf(OBJ)).toBeCloseTo(
      2 * (depthOf(move(-mmToPx(10), 1)) - depthOf(OBJ)),
      9,
    );
  });

  it("⭐ out and back RETURNS — it is a displacement, applied per frame", () => {
    const away = move(-mmToPx(25));
    const back = depthTranslate(CAM, away, push, AWAY, mmToPx(25), PER_PX, 1, minM, maxM);
    expect(length(sub(back, OBJ))).toBeCloseTo(0, 9);
  });

  it("zero travel changes nothing", () => {
    expect(length(sub(move(0), OBJ))).toBeCloseTo(0, 12);
  });
});

describe("⛔⛔ WHICH WAY IS AWAY depends on the camera's side of the horizon", () => {
  // ⚠⚠ THE DEFECT THESE PIN, FOUND BY FINGER: "when the camera is on the bottom ring
  // facing upwards, the depth translation is chaotic." An object pushed further off along
  // the ground RISES toward the horizon seen from above and SINKS seen from below — so a
  // rule that hard-codes "fingers up means away" is right on the top rings and BACKWARDS on
  // the bottom one. ⭐ A hand correcting a backwards control produces exactly that chaos.

  const UP_VIEW: Vec3 = normalize([0, 0.7, 0.7])!; // a camera below, looking up
  const upPush = gravityFrame(UP_VIEW, DOWN)!.depth!;
  const upDepthOf = (q: Vec3) => dot(sub(q, CAM), upPush);

  it("⭐ looking DOWN on the scene, fingers UP push the object away", () => {
    expect(depthOf(move(mmToPx(-20)))).toBeGreaterThan(depthOf(OBJ));
  });

  it("⛔⛔ looking UP from below, the SAME fingers bring it CLOSER — the sign must flip", () => {
    const out = depthTranslate(
      CAM, OBJ, upPush, Math.sign(dot(UP_VIEW, DOWN)), mmToPx(-20), PER_PX, 1, minM, maxM,
    );
    expect(upDepthOf(out)).toBeLessThan(upDepthOf(OBJ));
  });

  it("⛔ COUNTER-EXAMPLE: forcing the old hard-coded +1 from below inverts the gesture", () => {
    // ⭐ This is what shipped, and it is what the hand felt. Kept so the fix cannot be
    // quietly undone by someone "simplifying" the sign away.
    const wrong = depthTranslate(CAM, OBJ, upPush, 1, mmToPx(-20), PER_PX, 1, minM, maxM);
    const right = depthTranslate(
      CAM, OBJ, upPush, Math.sign(dot(UP_VIEW, DOWN)), mmToPx(-20), PER_PX, 1, minM, maxM,
    );
    expect(Math.sign(upDepthOf(wrong) - upDepthOf(OBJ))).toBe(
      -Math.sign(upDepthOf(right) - upDepthOf(OBJ)),
    );
  });

  it("⛔ a LEVEL camera shows nothing for a depth change, so the gesture goes quiet", () => {
    // ⚠ The fifth appearance of "goes quiet before it fails", and the first with the quiet
    // zone in the MIDDLE of the range rather than at an end.
    const level: Vec3 = normalize([0, 0, 1])!;
    expect(Math.sign(dot(level, DOWN))).toBe(0);
    const out = depthTranslate(
      CAM, OBJ, gravityFrame(level, DOWN)!.depth!, 0, mmToPx(-20), PER_PX, 1, minM, maxM,
    );
    expect(out).toEqual(OBJ);
  });
});

describe("⛔ the clamps and the degenerate cases", () => {
  it("cannot be pulled onto the camera", () => {
    expect(depthOf(move(mmToPx(100000)))).toBeCloseTo(minM, 9);
    expect(minM).toBeGreaterThan(CAMERA_NEAR_PLANE_M);
  });

  it("cannot be pushed past the camera's own maximum orbit radius", () => {
    expect(depthOf(move(-mmToPx(100000)))).toBeCloseTo(maxM, 9);
  });

  it("⭐ both bounds are DERIVED — no new tunable to measure", () => {
    expect(minM).toBe(2 * CAMERA_NEAR_PLANE_M);
    expect(maxM).toBe(DEFAULT_CONFIG.cameraRadiusMaxM);
  });

  it("⛔ a camera looking STRAIGHT DOWN has no depth direction", () => {
    // ⭐⭐ THE FRAME ITSELF REFUSES, which is a STRONGER statement than the one this vector
    // used to make. `depthPushDirection` returned a null *direction*; `gravityFrame` returns
    // **no frame at all** — looking straight down there is no horizontal view axis to flatten,
    // so neither depth NOR the roll axis exists, and the caller cannot get half an answer.
    expect(gravityFrame([0, -1, 0], DOWN)).toBeNull();
    expect(depthTranslate(CAM, OBJ, [0, 0, 0], 1, mmToPx(-20), PER_PX, 1, minM, maxM)).toEqual(
      OBJ,
    );
  });

  it("⛔ an object BEHIND the camera is left alone", () => {
    const behind: Vec3 = [0, 0.1, -3];
    expect(move(mmToPx(-20), 1, behind)).toEqual(behind);
  });

  it("⛔ never writes a NaN — one would never wash out of a placement", () => {
    for (const bad of [NaN, Infinity]) {
      for (const c of depthTranslate(CAM, OBJ, push, AWAY, bad, PER_PX, 1, minM, maxM)) {
        expect(Number.isFinite(c)).toBe(true);
      }
      for (const c of depthTranslate(CAM, OBJ, push, AWAY, mmToPx(-20), bad, 1, minM, maxM)) {
        expect(Number.isFinite(c)).toBe(true);
      }
    }
  });
});

// ══════════════════════════════════════════════════════════════════════════════
// ⭐⭐⭐ A12 — THE SECOND FINGER DRIVES BOTH: x IS ROLL, y IS DEPTH
//
// > *"One touchpoint idle on object && second touchpoint inside or outside any object &&
// > delta position y -> depth translation control. One touchpoint idle on object && second
// > touchpoint inside or outside any object && delta position x -> roll rotation control.
// > This will remove the conflict and decision lag between yaw/pitch and roll and the jump
// > on roll that we have currently due to all being controlled by the one touchpoint."*
//
// ⭐⭐ THE AMBIGUITY IS DISSOLVED BY MOVING THE GESTURE, NOT BY DECIDING BETTER. Yaw/pitch
// is ONE touchpoint; roll is TWO. They are no longer the same hand shape, so nothing has to
// tell them apart — no `rollAngle` commit threshold, no circle fit, no provisional motion,
// no rebase, and **no jump**.
//
// ⭐ And it composes with the per-axis deadband (A11) exactly: the second finger's x and y
// break out INDEPENDENTLY, so a mostly-horizontal drag is pure roll and a mostly-vertical
// one is pure depth. ⛔ A radial band would have made every diagonal do both.
// ══════════════════════════════════════════════════════════════════════════════

describe("⭐⭐⭐ A12 — the second finger's axis, as `A16` narrowed it", () => {
  const MOV = "MOVING" as const;
  const STI = "STATIONARY" as const;
  // ⛔⛔ THIS SUITE WAS REWRITTEN ON 2026-09-16 (`D28`) AND THE OLD ASSERTIONS ARE THE
  // RECORD OF WHAT CHANGED. `A12` gave the second finger BOTH axes at once — x rolls, y
  // pushes depth, kept independent by `A11`'s per-axis bands — and its vectors asserted a
  // diagonal drag doing both. ⭐ `A16` narrowed it to ONE axis chosen by the mode, and with
  // forks A and B deleted that narrowing is the only behaviour left, so those assertions
  // would now be false. ⚠ What survives unchanged is everything `A12` was really about:
  // the per-axis TEST and the travel passing through unscaled. ⛔ *Rule 6 winning while the
  // holder moves* did NOT survive — see the vector below; the owner wanted both at once.

  it("⭐⭐ in ROTATE the x axis rolls, and y is suppressed", () => {
    const d = secondFingerDrive({ x: MOV, y: MOV }, { dx: 12, dy: -7 }, "ROTATE");
    expect(d.rollDxPx).toBe(12);
    expect(d.depthDyPx).toBe(0);
  });

  it("⭐⭐ in TRANSLATE the y axis pushes depth, and x is suppressed", () => {
    const d = secondFingerDrive({ x: MOV, y: MOV }, { dx: 12, dy: -7 }, "TRANSLATE");
    expect(d.depthDyPx).toBe(-7);
    expect(d.rollDxPx).toBe(0);
  });

  it("⛔ THE PER-AXIS TEST STILL DECIDES: a still axis contributes nothing", () => {
    // ⭐ `A11`'s bands are what make this possible — the chosen axis must break out of its
    // own corridor, so a mostly-vertical drag in ROTATE mode still rolls nothing.
    // ⚠⚠ AND THIS IS THE ONE GUARD LEFT now that the holder is not consulted: without it a
    // resting second finger would roll the object with its jitter, which is what `A11`'s
    // per-axis deadband exists to prevent. ⛔ It is why *"simultaneous"* is safe at all.
    expect(secondFingerDrive({ x: STI, y: MOV }, { dx: 0, dy: -9 }, "ROTATE").rollDxPx).toBe(0);
    expect(secondFingerDrive({ x: MOV, y: STI }, { dx: 12, dy: 0 }, "TRANSLATE").depthDyPx).toBe(0);
  });

  it("✅✅ BOTH FINGERS DRIVE AT ONCE — the holder's motion is not consulted at all", () => {
    // ⛔⛔ THIS VECTOR ASSERTED THE OPPOSITE UNTIL 2026-09-17, and the retraction is the
    // record: *"NOTHING happens while the finger ON THE OBJECT is moving — that is rule 6"*,
    // because `A10`'s gate made the two rules a PARTITION of the two-finger configuration.
    //
    // ⭐ The owner rejected the partition itself: *"each touchpoint have to wait that the
    // other idle for its input to get integrated. I want everything simultaneous."*
    // ✅ So each finger owns its own channel and they SUM — the same way the holder's own x
    // and y already do. ⚠ `secondFingerDrive` no longer takes the holder's state, which is
    // the strongest form the change can take: the question cannot be asked at all.
    for (const t of ["TRANSLATE", "ROTATE"] as const) {
      const d = secondFingerDrive({ x: MOV, y: MOV }, { dx: 12, dy: -7 }, t);
      expect(t === "ROTATE" ? d.rollDxPx : d.depthDyPx).not.toBe(0);
    }
  });

  it("⛔ a still hand does nothing", () => {
    const d = secondFingerDrive({ x: STI, y: STI }, { dx: 0, dy: 0 }, "TRANSLATE");
    expect(d.rollDxPx).toBe(0);
    expect(d.depthDyPx).toBe(0);
  });

  it("⭐ it passes the travel through UNCHANGED — the gate decides, it does not scale", () => {
    for (const v of [0.4, 1, 7.5, -3.2, 120]) {
      expect(
        secondFingerDrive({ x: MOV, y: MOV }, { dx: v, dy: v }, "ROTATE").rollDxPx,
      ).toBe(v);
      expect(
        secondFingerDrive({ x: MOV, y: MOV }, { dx: v, dy: v }, "TRANSLATE").depthDyPx,
      ).toBe(v);
    }
  });
});

describe("⭐ A12's roll angle is a DRAG, not a swept circle", () => {
  it("⭐⭐ degrees are proportional to MILLIMETRES of travel, not to pixels", () => {
    // ⛔ Rule 3: thresholds and gains are millimetres on the physical screen. A degrees-
    // per-PIXEL gain would roll a phone and a tablet by different amounts for the same
    // hand movement.
    const gain = 2; // degrees per millimetre
    expect(rollDragDeg(mmToPx(10), gain)).toBeCloseTo(20, 9);
    expect(rollDragDeg(mmToPx(-4.5), gain)).toBeCloseTo(-9, 9);
  });

  it("⭐ zero travel is zero roll, and the sign follows the drag", () => {
    expect(rollDragDeg(0, 3)).toBe(0);
    expect(rollDragDeg(mmToPx(1), 3)).toBeGreaterThan(0);
    expect(rollDragDeg(mmToPx(-1), 3)).toBeLessThan(0);
  });

  it("⭐⭐ it is INCREMENTAL — the same drag applied twice turns twice as far", () => {
    // ⚠ The old roll was an ABSOLUTE swept angle against a baseline, and that baseline is
    // exactly what went stale and produced the jump. An increment has no baseline to lose.
    const gain = 1.5;
    const once = rollDragDeg(mmToPx(6), gain);
    expect(rollDragDeg(mmToPx(12), gain)).toBeCloseTo(2 * once, 9);
  });
});

// ══════════════════════════════════════════════════════════════════════════════
// ⭐⭐⭐ A13 — THE WHOLE TWO-TOUCHPOINT TABLE, AS ONE FUNCTION
//
// > *"One touchpoint on object && delta position x or y -> horizontal x or gravity axis
// > translation. One touchpoint on object idle && second touchpoint anywhere with delta
// > position y -> horizontal depth translation. One touchpoint on object with delta
// > position x or y && second touchpoint idle anywhere -> rotation on yaw along gravity
// > axis or pitch along horizontal x axis. One touchpoint on object idle && second
// > touchpoint anywhere with delta position x -> roll rotation along horizontal depth
// > axis."*
//
// ⭐⭐ THE SHAPE OF IT: **whichever finger MOVES is the one that acts, and the OTHER one's
// state says which rule.** Four cells, no overlap, nothing to arbitrate over time.
//
//              second absent   second IDLE      second MOVING
//   holder MOVING  translate      ROTATE          translate (⚠ see below)
//   holder IDLE    —              —               x → roll, y → depth
//
// ⛔⛔ ONE CELL THE OWNER DID NOT NAME: both fingers moving. It is resolved as TRANSLATE —
// the holder wins every tie, as it has since A10, and it is what the build already did. The
// alternative (do nothing until one of them settles) reintroduces exactly the decision lag
// A12 was written to delete.
// ══════════════════════════════════════════════════════════════════════════════

// ⛔⛔ THE FORK A AND FORK B SUITES WERE DELETED HERE, 2026-09-16 (`D28`).
//
// ⭐ They asserted `holderDrive` — fork A: one touchpoint translates, a second held still
// rotates; fork B: the spec's inversion — and the *exact opposites* invariant that justified
// running both from one build. The owner closed fork C on the glass and chose it, so the
// function and both suites are gone rather than left dormant.
// ⚠ The account of all three forks, why a flag beat two branches, and what each one did is
// one tier down in `Claude/00_CORE/queue_notes/IN13.md`. ⛔ A deleted vector whose subject no
// longer exists is not a loss of coverage; a dormant one would have been a trap.

// ══════════════════════════════════════════════════════════════════════════════
// ⭐⭐⭐ A14 — A LIFT-AND-REPLACE OF THE SECOND TOUCHPOINT IS **ONE** GESTURE
//
// > *"1- one touchpoint on object -> it translates -> second touchpoint pressed on screen
// > outside any object -> object immediately rotates -> everything is OK.
// > 2- …second touchpoint is released then pressed on screen outside any object and I WAIT
// > to input delta position the first touchpoint -> first object rotates -> OK.
// > 3- …and I IMMEDIATELY input delta position the first touchpoint -> first object
// > continues to translate for a while then rotates -> this is the issue."*
//
// ⭐⭐ THE DIAGNOSIS, AND THE MODE LOGIC WAS NEVER WRONG. Between the lift and the press
// there is genuinely **ONE touchpoint down**, and A13 says one touchpoint TRANSLATES. So:
//
//   * case 3 — the holder keeps moving THROUGH the swap, so it translates for exactly as
//     long as the swap takes: a lift and a replace is 150–300 ms of hand, which is very
//     visible;
//   * case 2 — the holder is still during the swap, so the same interval produces nothing
//     to see and the mode is already right by the time it moves;
//   * case 1 — there is no lift at all, so there is no interval.
//
// ⛔ Cases 2 and 3 differ ONLY by whether the holder happens to be moving during the gap —
// which is exactly the owner's *"cases 2 and 3 differ by timing of the input"*.
//
// ⭐⭐⭐ SO THE RULE IS RIGHT AND THE GESTURE MODEL IS WRONG: a lift-and-replace is ONE
// intention, and dropping to one-touchpoint behaviour in the middle of it is the artefact.
// ⛔ The grace is keyed on a LIFT — discrete, deliberate, visible — never on a motion
// state, which is the rule the previous round cost us.
// ══════════════════════════════════════════════════════════════════════════════

// ⛔⛔ A14's SUITE WAS DELETED HERE, 2026-09-16 (`D28`), AND THE REASON IS THE INTERESTING
// PART. `A14` gave a second touchpoint a **grace** after it lifted, so that a lift-and-replace
// read as ONE gesture: without it the 150-300 ms gap has genuinely one touchpoint down, and a
// mode keyed on PRESENCE fell through it.
// ⭐⭐ **The mode is no longer keyed on presence** — a tap decides it — so the gap cannot be
// fallen through and the grace has nothing left to protect. ⚠ It had already become decoration:
// its only remaining readers were a HUD line and a slider, which is exactly the dead-tunable
// shape `config_debt.test.ts` refuses and the same trap as the HUD's retired roll line.
// ⛔ So `secondTouchHeld`, `secondTouchGraceMs` and the lift timestamp are **deleted**, not
// left dormant. ⭐ `A14`'s text stands in `AMENDMENTS_R5.md` as the record of a defect that
// can no longer occur, and `queue_notes/IN4.md` keeps its device narrative.

describe("⭐⭐⭐ A16 — the mode picks DEPTH or ROLL for the second finger, never both", () => {
  const MOV2 = "MOVING" as const;
  const STI2 = "STATIONARY" as const;
  const both = { x: MOV2, y: MOV2 };
  const step = { dx: 12, dy: -7 };

  it("⭐⭐ TRANSLATE keeps DEPTH and suppresses roll", () => {
    // ⭐ The pairing is by KIND: the holder's screen-plane drag and the second finger's
    // depth are both translations, so one toggle answers for both fingers.
    const d = secondFingerDrive(both, step, "TRANSLATE");
    expect(d.depthDyPx).toBe(-7);
    expect(d.rollDxPx).toBe(0);
  });

  it("⭐⭐ ROTATE keeps ROLL and suppresses depth", () => {
    const d = secondFingerDrive(both, step, "ROTATE");
    expect(d.rollDxPx).toBe(12);
    expect(d.depthDyPx).toBe(0);
  });

  it("⛔⛔ NEVER BOTH — the owner's words, as an invariant over every combination", () => {
    // ⚠ Including a pure diagonal, which under A12 drives both at once: in fork C it must
    // do exactly one, so half a roll cannot arrive by accident during a depth push.
    for (const axes of [both, { x: MOV2, y: STI2 }, { x: STI2, y: MOV2 }]) {
      for (const t of ["TRANSLATE", "ROTATE"] as const) {
        const d = secondFingerDrive(axes, { dx: 5, dy: 5 }, t);
        expect(d.rollDxPx === 0 || d.depthDyPx === 0).toBe(true);
      }
    }
  });

  it("⛔⛔ A12's TWO-AXES-AT-ONCE IS NOW UNREACHABLE, and that is the trade", () => {
    // ⭐⭐ THIS VECTOR REPLACES ONE THAT ASSERTED THE OPPOSITE. It used to prove that forks A
    // and B kept `A12` exactly — a diagonal second drag driving roll AND depth together —
    // and that fork C's narrowing could not reach them. ⛔ With A and B deleted (`D28`) the
    // narrowing is the only behaviour left, so the honest assertion is the consequence:
    // there is no mode in which both axes move, for any input.
    // ⚠ `A12`'s per-axis bands still do their work; what is gone is the diagonal that did
    // half of each. The cost — a roll and a depth push need a tap between them — is the
    // point, and it was closed on the glass.
    for (const t of ["TRANSLATE", "ROTATE"] as const) {
      for (const axes of [both, { x: MOV2, y: STI2 }, { x: STI2, y: MOV2 }]) {
        const d = secondFingerDrive(axes, { dx: 9, dy: 9 }, t);
        expect(d.rollDxPx === 0 || d.depthDyPx === 0).toBe(true);
      }
    }
  });

  it("⛔ the A10 GATE still comes first — a moving holder drives neither, in every fork", () => {
    // ✅✅ RETRACTED 2026-09-17, like its twin above: the narrowing is not a mask on a gate,
    // because there is no gate. ⛔ The owner wants both fingers integrated at once, so with
    // the holder moving the second finger STILL contributes its axis — and the mode still
    // picks which axis that is, which is all `A16` ever claimed.
    for (const t of ["TRANSLATE", "ROTATE"] as const) {
      const d = secondFingerDrive(both, step, t);
      expect(t === "ROTATE" ? d.rollDxPx : d.depthDyPx).not.toBe(0);
      expect(t === "ROTATE" ? d.depthDyPx : d.rollDxPx).toBe(0);
    }
  });
});
