/**
 * AMENDMENT A10 — DEPTH TRANSLATION BY A STILL HOLDER AND A MOVING ANCHOR.
 *
 * ⛔⛔ THIS FILE REPLACES A6's VECTORS, AND THE REASON IS THE WHOLE POINT. A6 asked whether
 * two fingers were travelling TOGETHER, which is a question with no answer for a window at
 * the start of every gesture and again at every reversal — and the owner rejected the
 * result on the glass: *"I don't like the conflict generated by the control of depth
 * translation by two fingers."*
 *
 * ⭐⭐ A10 ASKS A QUESTION THAT IS ALWAYS ANSWERABLE: is the finger ON THE OBJECT still?
 * If it is, the other finger's vertical travel is depth. If it is not, the gesture is rule
 * 6 and the other finger is an anchor. ⛔ There is no window, no ratio and no tolerance, so
 * there is nothing to wait for and nothing to tune.
 *
 * ⭐ And it is the SPEC's own vocabulary: §1.1 says *"every 'delta position' in the spec
 * means MOVING; every 'no delta position' means STATIONARY."* The gate reads the hysteretic
 * motion state, not a speed invented here.
 *
 * ⭐⭐ `METHOD`, and the reason this file composes two real `MotionTracker`s rather than
 * passing literal states: *a composition is a thing to MEASURE, not an emergent property.*
 * The gate itself is trivial; what a hand judges is the gate ON TOP OF the motion state,
 * with a real finger's noise in it.
 *
 * ⭐ HEIGHT NEVER CHANGES is carried over from A5 and still asserted: the push direction is
 * perpendicular to gravity by construction, and gravity is the primary constraint here.
 */
import { describe, expect, it } from "vitest";
import {
  depthGate,
  depthLimits,
  depthPushDirection,
  depthTranslate,
} from "../src/input/depth_translate";
import { MotionTracker, type MotionState, type Sample } from "../src/input/motion";
import { DEFAULT_CONFIG, CAMERA_NEAR_PLANE_M } from "../src/input/gestureConfig";
import { dot, length, normalize, scale, sub, type Vec3 } from "../src/core/vec";
import { mmToPx } from "../src/core/units";

const NOISE_MM = 0.761; // ⭐ MEASURED, 2026-09-14.

const DOWN: Vec3 = [0, -1, 0];
const CAM: Vec3 = [0, 0.8, -1.2];
const VIEW: Vec3 = normalize([0, -0.5, 1])!;
const OBJ: Vec3 = [0.15, 0.1, 0.1];
const { minM, maxM } = depthLimits(DEFAULT_CONFIG);
const PER_PX = 0.002; // rule 6's computed factor, at some camera distance

const push = depthPushDirection(VIEW, DOWN)!;
const depthOf = (p: Vec3) => dot(sub(p, CAM), push);
/** ⭐ +1: this fixture's camera looks DOWN on the scene, so "away" rises on screen. */
const AWAY = Math.sign(dot(VIEW, DOWN));
const move = (dyPx: number, gain = 1, obj: Vec3 = OBJ) =>
  depthTranslate(CAM, obj, push, AWAY, dyPx, PER_PX, gain, minM, maxM);

// ══════════════════════════════════════════════════════════════════════════════
// ⭐⭐ THE GATE, COMPOSED WITH THE REAL MOTION STATE
// ══════════════════════════════════════════════════════════════════════════════

/** A finger, tracked exactly as the scene tracks one. */
class Finger {
  readonly tracker = new MotionTracker(DEFAULT_CONFIG);
  private seed: number;
  state: MotionState = "STATIONARY";
  constructor(
    public x: number,
    public y: number,
    seed: number,
  ) {
    this.seed = seed;
  }
  /** ⭐ The MEASURED pointer noise, on every sample. A noiseless fixture proves nothing. */
  private jitterPx(): number {
    this.seed = (this.seed * 1103515245 + 12345) & 0x7fffffff;
    return mmToPx(((this.seed / 0x7fffffff) * 2 - 1) * NOISE_MM);
  }
  push(t: number, dyMm = 0): MotionState {
    this.y += mmToPx(dyMm);
    const s: Sample = { x: this.x + this.jitterPx(), y: this.y + this.jitterPx(), t };
    this.state = this.tracker.push(s);
    return this.state;
  }
}

/** Run `n` samples 8 ms apart, returning the gate verdict at each one. */
const run = (
  holder: Finger,
  anchor: Finger,
  n: number,
  step: (i: number) => readonly [number, number],
  t0 = 0,
) => {
  const out: string[] = [];
  for (let i = 0; i < n; i++) {
    const [holderDyMm, anchorDyMm] = step(i);
    const t = t0 + i * 8;
    holder.push(t, holderDyMm);
    anchor.push(t, anchorDyMm);
    out.push(depthGate(holder.state, anchor.state));
  }
  return out;
};

const STILL = () => [0, 0] as const;

describe("⭐⭐ A10 — the gate is the HOLDER's stillness, and nothing else", () => {
  it("⭐⭐ a STILL holder and a MOVING anchor is DEPTH", () => {
    const holder = new Finger(400, 400, 11);
    const anchor = new Finger(200, 600, 97);
    const v = run(holder, anchor, 40, () => [0, -1.2] as const);
    // ⛔ It need not open on the FIRST sample — §1.1's MOVING transition takes
    // `moveEnterDistance` of net travel, which is the same threshold every other rule
    // waits for. What matters is that it opens and then STAYS open.
    expect(v).toContain("DEPTH");
    expect(v.slice(20).every((g) => g === "DEPTH")).toBe(true);
  });

  it("⛔⛔ a MOVING holder is RULE 6, whatever the anchor does — the holder wins", () => {
    // ⚠ This is the case A6 could not answer without a window: both fingers travelling.
    const holder = new Finger(400, 400, 5);
    const anchor = new Finger(200, 600, 31);
    const v = run(holder, anchor, 40, () => [-1.2, -1.2] as const);
    expect(v.slice(20).every((g) => g === "IDLE")).toBe(true);
  });

  it("⛔ a still hand is neither", () => {
    const holder = new Finger(400, 400, 7);
    const anchor = new Finger(200, 600, 13);
    expect(run(holder, anchor, 40, STILL).every((g) => g === "IDLE")).toBe(true);
  });

  it("⭐⭐ THROUGH A REVERSAL THE GATE NEVER BLAMES THE HOLDER — A6's ambiguity is GONE", () => {
    // ⛔⛔ The owner named this against A6: *"at the moment of direction reversion, both
    // delta position y converge to zero before changing sign (maybe one before the other):
    // this is the moment an ambiguity can occur."* ⭐ Under A10 the reversal is a property
    // of the ANCHOR alone, and the holder — the thing actually being asked about — never
    // moved, so there is nothing to misread.
    const holder = new Finger(400, 400, 17);
    const anchor = new Finger(200, 600, 23);
    run(holder, anchor, 30, () => [0, -1.5] as const);
    // …and back, through a genuine dwell at the turn.
    const back = run(holder, anchor, 60, (i) => [0, i < 10 ? 0 : 1.5] as const, 240);
    // ⚠ The anchor genuinely stops at the turn, so the gate genuinely closes — that is
    // CORRECT, not a flicker: a still anchor is not a depth drag. ⭐ What must not happen
    // is the holder being blamed for it, and the gate must be DEPTH again as soon as the
    // anchor moves, with no second wait.
    expect(back.slice(-15).every((g) => g === "DEPTH")).toBe(true);
    expect(holder.state).toBe("STATIONARY");
  });

  it("⭐⭐ A LATE-STARTING ANCHOR COSTS NOTHING — A6's second ambiguity is GONE", () => {
    // ⛔ Under A6 a lagging second finger looked like rule 6, so the vertical had to be
    // WITHHELD for up to two windows and that travel was DISCARDED. Here the holder is
    // still, so there is no vertical to withhold and nothing to discard.
    const holder = new Finger(400, 400, 41);
    const anchor = new Finger(200, 600, 59);
    const idle = run(holder, anchor, 25, STILL);
    expect(idle.every((g) => g === "IDLE")).toBe(true);
    const going = run(holder, anchor, 40, () => [0, -1.2] as const, 200);
    expect(going.slice(20).every((g) => g === "DEPTH")).toBe(true);
  });

  it("⛔⛔ A SLOW PERSISTENT CREEP OF THE HOLDER CLOSES THE GATE", () => {
    // ⚠⚠ THE ONE THING THAT COULD MAKE THIS RULE LIE. A holder that creeps below
    // `stillSpeed` is never *at rest*, and an instantaneous speed test would call it still
    // for ever — so the object would be pushed in depth while the hand was, in fact,
    // dragging it. ⭐ §1.1's settle-excursion bound (`moveExitDistance`) is exactly the
    // guard for that, and composing the two is what proves the gate inherits it.
    const holder = new Finger(400, 400, 71);
    const anchor = new Finger(200, 600, 83);
    const v = run(holder, anchor, 60, () => [0.25, -1.2] as const);
    expect(v.slice(-20).every((g) => g === "IDLE")).toBe(true);
    expect(holder.state).toBe("MOVING");
  });

  it("⛔⛔ COUNTER-EXAMPLE: 'both fingers moving' would call the rule-6 drag DEPTH", () => {
    // ⭐ The discriminator stated as a number, so *"the gate is the holder's stillness"* is
    // a checkable claim rather than a description. A gate defined the naive way — both
    // fingers in motion — inverts the second vector above.
    const holder = new Finger(400, 400, 5);
    const anchor = new Finger(200, 600, 31);
    const naive: string[] = [];
    for (let i = 0; i < 40; i++) {
      holder.push(i * 8, -1.2);
      anchor.push(i * 8, -1.2);
      naive.push(holder.state === "MOVING" && anchor.state === "MOVING" ? "DEPTH" : "IDLE");
    }
    expect(naive.slice(20).every((g) => g === "DEPTH")).toBe(true);
    expect(depthGate(holder.state, anchor.state)).toBe("IDLE");
  });

  it("⛔ the gate is a PURE function of the two states — all four cases", () => {
    expect(depthGate("STATIONARY", "MOVING")).toBe("DEPTH");
    expect(depthGate("STATIONARY", "STATIONARY")).toBe("IDLE");
    expect(depthGate("MOVING", "MOVING")).toBe("IDLE");
    expect(depthGate("MOVING", "STATIONARY")).toBe("IDLE");
  });
});

// ══════════════════════════════════════════════════════════════════════════════

describe("⭐⭐ HEIGHT NEVER CHANGES — gravity is the primary constraint", () => {
  it("at every camera elevation", () => {
    for (const tilt of [0.1, 0.5, 1.5, 4]) {
      const view = normalize([0, -tilt, 1])!;
      const out = depthTranslate(CAM, OBJ, depthPushDirection(view, DOWN)!, Math.sign(dot(view, DOWN)), mmToPx(-20), PER_PX, 1, minM, maxM);
      expect(out[1], `tilt ${tilt}`).toBeCloseTo(OBJ[1], 12);
    }
  });

  it("⛔ and the across-view offset is untouched too — only the depth moves", () => {
    const across = (p: Vec3) => {
      const r = sub(p, CAM);
      return sub(sub(r, scale(push, dot(r, push))), scale(DOWN, dot(r, DOWN)));
    };
    expect(length(sub(across(move(mmToPx(-30))), across(OBJ)))).toBeCloseTo(0, 12);
  });
});

describe("the sense and the size of the motion", () => {
  it("⚠ fingers UP push the object AWAY — it sits higher on screen when further off", () => {
    expect(depthOf(move(mmToPx(-20)))).toBeGreaterThan(depthOf(OBJ));
  });

  it("fingers DOWN bring it closer", () => {
    expect(depthOf(move(mmToPx(20)))).toBeLessThan(depthOf(OBJ));
  });

  it("⭐⭐ moves as far as RULE 6 would for the same travel — gain 1 means CONSISTENT, not tracking", () => {
    // 30 mm of finger at this camera factor: the same world distance a screen-plane drag
    // would cover, just pointed into the scene instead of across it.
    const travelPx = mmToPx(30);
    expect(depthOf(move(-travelPx)) - depthOf(OBJ)).toBeCloseTo(travelPx * PER_PX, 9);
  });

  it("is linear in the travel, and in the gain", () => {
    expect(depthOf(move(-mmToPx(30))) - depthOf(OBJ)).toBeCloseTo(
      3 * (depthOf(move(-mmToPx(10))) - depthOf(OBJ)),
      9,
    );
    expect(depthOf(move(-mmToPx(10), 2)) - depthOf(OBJ)).toBeCloseTo(
      2 * (depthOf(move(-mmToPx(10), 1)) - depthOf(OBJ)),
      9,
    );
  });

  it("⭐ out and back RETURNS — it is a displacement, applied per frame", () => {
    const away = move(-mmToPx(25));
    const back = depthTranslate(CAM, away, push, AWAY, mmToPx(25), PER_PX, 1, minM, maxM);
    expect(length(sub(back, OBJ))).toBeCloseTo(0, 9);
  });

  it("zero travel changes nothing", () => {
    expect(length(sub(move(0), OBJ))).toBeCloseTo(0, 12);
  });
});

describe("⛔⛔ WHICH WAY IS AWAY depends on the camera's side of the horizon", () => {
  // ⚠⚠ THE DEFECT THESE PIN, FOUND BY FINGER: "when the camera is on the bottom ring
  // facing upwards, the depth translation is chaotic." An object pushed further off along
  // the ground RISES toward the horizon seen from above and SINKS seen from below — so a
  // rule that hard-codes "fingers up means away" is right on the top rings and BACKWARDS on
  // the bottom one. ⭐ A hand correcting a backwards control produces exactly that chaos.

  const UP_VIEW: Vec3 = normalize([0, 0.7, 0.7])!; // a camera below, looking up
  const upPush = depthPushDirection(UP_VIEW, DOWN)!;
  const upDepthOf = (q: Vec3) => dot(sub(q, CAM), upPush);

  it("⭐ looking DOWN on the scene, fingers UP push the object away", () => {
    expect(depthOf(move(mmToPx(-20)))).toBeGreaterThan(depthOf(OBJ));
  });

  it("⛔⛔ looking UP from below, the SAME fingers bring it CLOSER — the sign must flip", () => {
    const out = depthTranslate(
      CAM, OBJ, upPush, Math.sign(dot(UP_VIEW, DOWN)), mmToPx(-20), PER_PX, 1, minM, maxM,
    );
    expect(upDepthOf(out)).toBeLessThan(upDepthOf(OBJ));
  });

  it("⛔ COUNTER-EXAMPLE: forcing the old hard-coded +1 from below inverts the gesture", () => {
    // ⭐ This is what shipped, and it is what the hand felt. Kept so the fix cannot be
    // quietly undone by someone "simplifying" the sign away.
    const wrong = depthTranslate(CAM, OBJ, upPush, 1, mmToPx(-20), PER_PX, 1, minM, maxM);
    const right = depthTranslate(
      CAM, OBJ, upPush, Math.sign(dot(UP_VIEW, DOWN)), mmToPx(-20), PER_PX, 1, minM, maxM,
    );
    expect(Math.sign(upDepthOf(wrong) - upDepthOf(OBJ))).toBe(
      -Math.sign(upDepthOf(right) - upDepthOf(OBJ)),
    );
  });

  it("⛔ a LEVEL camera shows nothing for a depth change, so the gesture goes quiet", () => {
    // ⚠ The fifth appearance of "goes quiet before it fails", and the first with the quiet
    // zone in the MIDDLE of the range rather than at an end.
    const level: Vec3 = normalize([0, 0, 1])!;
    expect(Math.sign(dot(level, DOWN))).toBe(0);
    const out = depthTranslate(
      CAM, OBJ, depthPushDirection(level, DOWN)!, 0, mmToPx(-20), PER_PX, 1, minM, maxM,
    );
    expect(out).toEqual(OBJ);
  });
});

describe("⛔ the clamps and the degenerate cases", () => {
  it("cannot be pulled onto the camera", () => {
    expect(depthOf(move(mmToPx(100000)))).toBeCloseTo(minM, 9);
    expect(minM).toBeGreaterThan(CAMERA_NEAR_PLANE_M);
  });

  it("cannot be pushed past the camera's own maximum orbit radius", () => {
    expect(depthOf(move(-mmToPx(100000)))).toBeCloseTo(maxM, 9);
  });

  it("⭐ both bounds are DERIVED — no new tunable to measure", () => {
    expect(minM).toBe(2 * CAMERA_NEAR_PLANE_M);
    expect(maxM).toBe(DEFAULT_CONFIG.cameraRadiusMaxM);
  });

  it("⛔ a camera looking STRAIGHT DOWN has no depth direction", () => {
    expect(depthPushDirection([0, -1, 0], DOWN)).toBeNull();
    expect(depthTranslate(CAM, OBJ, [0, 0, 0], 1, mmToPx(-20), PER_PX, 1, minM, maxM)).toEqual(
      OBJ,
    );
  });

  it("⛔ an object BEHIND the camera is left alone", () => {
    const behind: Vec3 = [0, 0.1, -3];
    expect(move(mmToPx(-20), 1, behind)).toEqual(behind);
  });

  it("⛔ never writes a NaN — one would never wash out of a placement", () => {
    for (const bad of [NaN, Infinity]) {
      for (const c of depthTranslate(CAM, OBJ, push, AWAY, bad, PER_PX, 1, minM, maxM)) {
        expect(Number.isFinite(c)).toBe(true);
      }
      for (const c of depthTranslate(CAM, OBJ, push, AWAY, mmToPx(-20), bad, 1, minM, maxM)) {
        expect(Number.isFinite(c)).toBe(true);
      }
    }
  });
});
