/**
 * ⭐ `D170`: the text of `scene1_demo_plan.ts` — shared by the script that writes it and the vector that
 * checks it, so the two cannot format it differently. ⚠ Engine-free data.
 */
import type { DemoPlan } from "../core/demo_plan";

export function formatDemoPlan(plan: DemoPlan): string {
  const moves = plan.moves.map((m) => "    " + JSON.stringify(m)).join(",\n");
  const start = Object.entries(plan.start)
    .map(([id, p]) => `    ${JSON.stringify(id)}: ${JSON.stringify(p)}`)
    .join(",\n");
  return `/**
 * ⛔ GENERATED by \`scripts/gen_demo_plan.ts\` from \`Scene_1\`'s final configuration (\`D170\`) — do not edit.
 * \`tests/d170.test.ts\` regenerates it and fails when it differs. → \`Claude/20_GAME_RULES/spec/DEMO_SCENE.md\`.
 */
import type { DemoPlan } from "../core/demo_plan";

export const SCENE1_DEMO_PLAN: DemoPlan = {
  seed: ${plan.seed},
  volume: ${JSON.stringify(plan.volume)},
  stage: ${JSON.stringify(plan.stage)},
  moves: [
${moves},
  ],
  start: {
${start},
  },
};
`;
}
