/**
 * ⭐ `D170`: writes `src/content/scene1_demo_plan.ts` — `Scene_1`'s demo plan, generated by
 * `core/demo_plan.ts` (`Claude/20_GAME_RULES/spec/DEMO_SCENE.md` §5). ⛔ Never edit that file by hand:
 * `tests/d170.test.ts` regenerates it and fails when it differs.
 * Run: `npx vite-node scripts/gen_demo_plan.ts`
 */
import { writeFileSync } from "node:fs";
import { SCENE_1 } from "../src/content/scene_1";
import { generateDemoPlan } from "../src/core/demo_plan";
import { formatDemoPlan } from "../src/content/demo_plan_format";

const plan = generateDemoPlan(SCENE_1);
writeFileSync(new URL("../src/content/scene1_demo_plan.ts", import.meta.url), formatDemoPlan(plan));
console.log(`wrote ${plan.moves.length} moves over ${Object.keys(plan.start).length} pieces`);
