/**
 * AMENDMENT **A10** — **DEPTH TRANSLATION BY A STILL HOLDER AND A MOVING ANCHOR.**
 *
 * Design of record: `Claude/10_INPUT_TOUCH/AMENDMENTS_R5.md` A10, superseding A6's
 * trigger. A5's GEOMETRY is untouched by both: depth is horizontal, and height never
 * changes.
 *
 * > The touchpoint **on the object is still**, and the touchpoint **outside it has a delta
 * > position in y** — the object translates in horizontal depth, by that anchor's travel.
 *
 * ## ⛔⛔ WHY A6 HAD TO GO, AND IT WAS FOUND BY FINGER
 *
 * A6 asked whether both fingers were travelling in y **together**, within a ratio, over a
 * window. ⚠ The owner: *"I don't like the conflict generated by the control of depth
 * translation by two fingers."*
 *
 * ⭐⭐ **THE FAULT WAS IN THE QUESTION, NOT IN THE ANSWER.** *"Are these two travels
 * equal?"* has **no answer** at two moments that occur in every single gesture:
 *
 * * **at a reversal**, both travels pass through zero — the ratio is jitter ÷ jitter;
 * * **at the start**, one finger has not moved yet — which is exactly rule 6's shape.
 *
 * A6 answered both by WAITING (two windows) and by WITHHOLDING rule 6's vertical
 * meanwhile, so the first window of travel was discarded and the hand felt a hesitation at
 * each end of every drag. ⛔ *"Is that finger still?"* is answerable at every instant,
 * including those two — so A10 needs no window, no ratio, no tolerance and no hold.
 *
 * ## ⛔ IT SHARES A CONFIGURATION WITH RULE 6, AND NOW THEY PARTITION IT
 *
 * | the finger ON the object | the other finger | rule |
 * |---|---|---|
 * | **MOVING** | anything | **rule 6** — translate; the holder drives |
 * | **STATIONARY** | MOVING in y | ⭐ **A10** — translate in DEPTH; the anchor drives |
 * | STATIONARY | STATIONARY | nothing |
 *
 * ⛔ **THE HOLDER WINS EVERY TIE**, so the two rules cannot both fire. That is the
 * property A6 never had.
 *
 * ⭐ And the roles swap cleanly with the intent: the finger that is *doing something* is
 * the one that drives. Rule 6's anchor was always a mode selector that contributed no
 * motion; here it contributes the motion and the object's own finger becomes the selector.
 *
 * ## ⭐ THE GAIN IS RULE 6's, REDIRECTED
 *
 * The displacement uses `trackingMetresPerPx` — the same computed factor rule 6 uses — so
 * **one hand's-worth of finger travel moves the object the same distance whichever
 * direction it is going**, in the screen plane or into the scene. ⛔ Not a
 * metres-per-millimetre constant, which rule 6 proved cannot serve both ends of a 20× zoom
 * clamp. `gainTranslateDepth` multiplies it, and 1.0 means *as far as a drag would*.
 *
 * ⚠ It is NOT "the object stays under the finger": that mapping diverges as the camera
 * levels out, because an object pushed along the ground barely moves on screen when you are
 * looking at it horizontally. ⭐ Consistency with rule 6 is a property that holds at every
 * camera elevation; tracking is not.
 *
 * ⛔ ENGINE-FREE.
 */
import { CAMERA_NEAR_PLANE_M, type GestureConfig } from "./gestureConfig";
import type { MotionState } from "./motion";
import type { Behaviour } from "./mode_toggle";
import { pxToMm } from "../core/units";
import { add, dot, normalize, scale, sub, type Vec3 } from "../core/vec";

/**
 * How near and how far a depth translation may drive an object, in metres of HORIZONTAL
 * depth. ⭐ Carried unchanged from A5: the bounds were derived, not invented, and changing
 * the TRIGGER does not change where an object may end up.
 *
 * * **The floor is twice the near plane.** `pinch.ts` records why: a zoom across the near
 *   plane produces *a black page with no error at all*. An object pushed onto the camera
 *   would clip through and invert behind it — the same silent failure, one object at a
 *   time.
 * * **The ceiling is the camera's own maximum orbit radius.** Beyond it the object cannot
 *   be brought back into view even by zooming all the way out. ⚠ A gesture must not reach a
 *   state the user cannot undo.
 *
 * ⚠ Whether the ceiling ever BINDS is on the HUD rather than asserted here — the owner
 * looked for it and could not see it, and a claim a device cannot check is an assertion.
 */
export function depthLimits(cfg: GestureConfig): { minM: number; maxM: number } {
  return { minM: 2 * CAMERA_NEAR_PLANE_M, maxM: cfg.cameraRadiusMaxM };
}

/**
 * The direction depth runs along: the camera's view direction with its gravity component
 * removed, normalised. `null` when there is none.
 *
 * ⛔⛔ HORIZONTAL, NOT ALONG THE VIEW AXIS — the owner's correction, and the reason is that
 * **gravity is the primary constraint in this game**. §2 rule 2ter anchors a face to it and
 * parts are assembled on a working plane, so a camera looking down would make "away" point
 * into the FLOOR. A gesture meaning *"put this further away"* must not change an object's
 * HEIGHT.
 *
 * ⛔ It vanishes when the camera looks straight down, and the orbit surface's top ring is a
 * steep look-down. ⚠ The MECHANISM of the weakening is the camera's POSITION, not its
 * angle: flattening does not turn the view direction, so what shrinks is the horizontal
 * distance as the camera climbs overhead.
 */
export function depthPushDirection(viewAxis: Vec3, gravityDown: Vec3): Vec3 | null {
  const g = normalize(gravityDown);
  const v = normalize(viewAxis);
  if (!g || !v) return null;
  return normalize(sub(v, scale(g, dot(v, g))));
}

/**
 * ⭐⭐ **A10's GATE.** Is this hand asking for depth?
 *
 * @param holder the motion state of the touchpoint **on the object** — the one whose
 *   raycast hit it.
 * @param anchor the motion state of the touchpoint **outside every object**.
 *
 * ⛔⛔ THE HOLDER'S STILLNESS IS THE WHOLE DISCRIMINATOR, AND IT IS THE ONLY QUESTION
 * ASKED. A6 asked whether the two fingers were travelling *together*, which is a question
 * with **no answer** for a window at the start of every gesture and again at every
 * reversal, where both travels pass through zero and the ratio becomes jitter ÷ jitter.
 * ⭐ *"Is that finger still?"* is answerable at every instant, including those two.
 *
 * ⭐ It is also §1.1's own vocabulary: *"every 'delta position' in the spec means MOVING;
 * every 'no delta position' means STATIONARY."* ⛔ So the gate takes MOTION STATES, never
 * a speed or a delta of its own — a second definition of *moving* would be free to
 * disagree with the one every other rule uses.
 *
 * ⚠ **A hysteretic state is what makes this safe, and an instantaneous one would not be.**
 * A resting finger jitters over the measured 0.761 mm, and a finger can CREEP below any
 * speed threshold indefinitely. §1.1 answers both: `moveEnterDistance` is net displacement
 * from an anchor, and `moveExitDistance` bounds the excursion during settle candidacy. The
 * gate inherits both by reading the state rather than the samples.
 *
 * ⛔ THE HOLDER WINS EVERY TIE. If both fingers move, it is rule 6 — the object follows
 * the finger touching it. That is not a tie-break invented here; it is what makes the two
 * rules a partition instead of an overlap.
 */
export function depthGate(holder: MotionState, anchor: MotionState): DepthVerdict {
  return holder === "STATIONARY" && anchor === "MOVING" ? "DEPTH" : "IDLE";
}

/** What the gate decided. ⭐ Two states, because there is nothing to be undecided about. */
export type DepthVerdict = "DEPTH" | "IDLE";

/**
 * Move an object in horizontal depth by one frame's common travel.
 *
 * @param push     the horizontal direction depth runs along — `GravityFrame.depth`.
 * @param awaySign +1 when moving the object AWAY makes it rise on screen (the camera looks
 *   DOWN on the scene), −1 when it makes it sink (the camera looks UP from below).
 *   ⛔⛔ IT IS NOT A CONSTANT, AND ASSUMING IT WAS WAS A DEFECT FOUND BY FINGER: *"when the
 *   camera is on the bottom ring facing upwards, the depth translation is chaotic."* An
 *   object further off along the ground rises toward the horizon seen from above and SINKS
 *   seen from below, so *fingers-up means away* is right on the top rings and backwards on
 *   the bottom one — and a hand correcting a backwards control produces exactly the chaos
 *   that was reported. ⭐ `Math.sign(GravityFrame.towardGravity)` is the value.
 *   ⚠ **0 at a level camera**, where a depth change produces no screen motion and there is
 *   nothing to follow. The gesture goes quiet rather than guessing a direction.
 * @param commonDyPx this frame's shared vertical travel, CSS pixels. ⚠ Screen y grows
 *   DOWNWARD.
 * @param metresPerPx `trackingMetresPerPx` for the camera — rule 6's computed factor, so a
 *   given finger travel moves the object as far into the scene as it would across it.
 *
 * ⛔ Returns the position UNCHANGED when there is no push direction or the object is not in
 * front of the camera — never a `NaN`, which would never wash out of a placement.
 */
export function depthTranslate(
  cameraPosition: Vec3,
  objectPosition: Vec3,
  push: Vec3,
  awaySign: number,
  commonDyPx: number,
  metresPerPx: number,
  gain: number,
  minM: number,
  maxM: number,
): Vec3 {
  const dir = normalize(push);
  if (!dir || !Number.isFinite(commonDyPx) || !Number.isFinite(metresPerPx)) {
    return objectPosition;
  }
  // ⛔ A level camera shows nothing for a depth change, so there is no direction to
  // follow. Suppress rather than pick one — `LESSONS_CARRIED` §6.
  const sign = Math.sign(awaySign);
  if (sign === 0 || !Number.isFinite(awaySign)) return objectPosition;

  const depth = dot(sub(objectPosition, cameraPosition), dir);
  if (!(depth > 0)) return objectPosition;

  // ⚠ NEGATED because screen y grows downward; ⭐ times `sign` because which way "away"
  // looks depends on whether the camera is above the scene or below it.
  const wanted = depth - commonDyPx * metresPerPx * gain * sign;
  const clamped = Math.min(maxM, Math.max(minM, wanted));
  // ⭐ Only the along-push component moves, so HEIGHT is untouched by construction.
  return add(objectPosition, scale(dir, clamped - depth));
}

/**
 * ⭐⭐⭐ **AMENDMENT A12** — what the SECOND touchpoint is asking for, per axis.
 *
 * > *"One touchpoint idle on object && second touchpoint inside or outside any object &&
 * > delta position y → depth translation control. …&& delta position x → roll rotation
 * > control. This will remove the conflict and decision lag between yaw/pitch and roll and
 * > the jump on roll."*
 *
 * ⭐⭐ THE AMBIGUITY IS DISSOLVED BY MOVING THE GESTURE, NOT BY DECIDING BETTER. Yaw/pitch
 * is ONE touchpoint; roll is TWO. They stopped being the same hand shape, so nothing has to
 * tell them apart — and everything that existed to do so is gone: the circle fit, the
 * `rollAngle` commit threshold, the provisional yaw/pitch, A8's rebase, and **the jump**.
 *
 * ⭐ It composes with A11's per-axis deadband exactly. The second finger's x and y break
 * out of their bands INDEPENDENTLY, so a mostly-horizontal drag is pure roll and a
 * mostly-vertical one is pure depth. ⛔ With one shared MOVING flag — or a radial band —
 * every diagonal would do both, and the object would creep away while you rolled it.
 *
 * ⛔ THE HOLDER WINS EVERY TIE, as in A10: while the finger on the object is moving this
 * returns nothing at all, because that is rule 6.
 *
 * ⛔ It DECIDES; it does not scale. A gate that also applied a gain would be a second gain,
 * free to disagree with the one in the config.
 */
export function secondFingerDrive(
  holder: MotionState,
  secondAxes: { readonly x: MotionState; readonly y: MotionState },
  secondStep: { readonly dx: number; readonly dy: number },
  toggled: Behaviour,
): { readonly rollDxPx: number; readonly depthDyPx: number } {
  // ⭐ A10's gate, asked per axis — the second finger drives only while the HOLDER is still.
  const gate = (axis: MotionState): boolean => depthGate(holder, axis) === "DEPTH";
  // ⛔⛔ ONE AXIS, NEVER BOTH, AND THE MODE PICKS IT (`A16`): *"depending on which is
  // toggled, the second touchpoint shall only control depth translation by delta position y
  // or roll by delta position x (not both). Switching between the two shall indeed require
  // the tap."*
  // ⭐⭐ THE PAIRING IS BY KIND, which is what makes one toggle enough for two fingers:
  // `TRANSLATE` pairs the holder's screen-plane drag with the second finger's **depth** —
  // both translations — and `ROTATE` pairs yaw/pitch with **roll**. One question, *am I
  // translating or rotating?*, and both fingers follow the same answer.
  // ⚠⚠ IT SUPERSEDES `A12`'s TWO-AXES-AT-ONCE, which is no longer reachable at all now that
  // forks A and B are deleted (`D28`). A12's per-axis bands still do the work of keeping the
  // corridors independent; what is gone is a diagonal driving roll AND depth together.
  // ⛔ What it costs, stated: a roll and a depth push need a tap between them. ⭐ That is the
  // point — no diagonal does half of each by accident.
  if (toggled === "ROTATE") {
    return { rollDxPx: gate(secondAxes.x) ? secondStep.dx : 0, depthDyPx: 0 };
  }
  return { rollDxPx: 0, depthDyPx: gate(secondAxes.y) ? secondStep.dy : 0 };
}

/**
 * ⭐ A12's roll: DEGREES from the second touchpoint's horizontal travel.
 *
 * @param dxPx      deadbanded horizontal travel, CSS pixels.
 * @param degPerMm  `gainRollDrag` — degrees of roll per MILLIMETRE of travel.
 *
 * ⛔ MILLIMETRES, rule 3: a degrees-per-PIXEL gain would roll a phone and a tablet by
 * different amounts for the same hand movement.
 *
 * ⭐⭐ AND IT IS AN INCREMENT, not an absolute angle against a baseline. ⚠ The old
 * 2quinte roll was a swept angle measured from a baseline, and that baseline going stale is
 * precisely what produced the jump at the commit — `lastRollDeg` tracked the uncommitted
 * phase, so ~60° was dropped at the moment the pose was rebased. An increment has no
 * baseline to lose.
 */
export function rollDragDeg(dxPx: number, degPerMm: number): number {
  return pxToMm(dxPx) * degPerMm;
}



