/**
 * AMENDMENT **A10** — **DEPTH TRANSLATION BY A STILL HOLDER AND A MOVING ANCHOR.**
 *
 * Design of record: `Claude/10_INPUT_TOUCH/AMENDMENTS_R5.md` A10, superseding A6's
 * trigger. A5's GEOMETRY is untouched by both: depth is horizontal, and height never
 * changes.
 *
 * > The touchpoint **on the object is still**, and the touchpoint **outside it has a delta
 * > position in y** — the object translates in horizontal depth, by that anchor's travel.
 *
 * ## ⛔⛔ WHY A6 HAD TO GO, AND IT WAS FOUND BY FINGER
 *
 * A6 asked whether both fingers were travelling in y **together**, within a ratio, over a
 * window. ⚠ The owner: *"I don't like the conflict generated by the control of depth
 * translation by two fingers."*
 *
 * ⭐⭐ **THE FAULT WAS IN THE QUESTION, NOT IN THE ANSWER.** *"Are these two travels
 * equal?"* has **no answer** at two moments that occur in every single gesture:
 *
 * * **at a reversal**, both travels pass through zero — the ratio is jitter ÷ jitter;
 * * **at the start**, one finger has not moved yet — which is exactly rule 6's shape.
 *
 * A6 answered both by WAITING (two windows) and by WITHHOLDING rule 6's vertical
 * meanwhile, so the first window of travel was discarded and the hand felt a hesitation at
 * each end of every drag. ⛔ *"Is that finger still?"* is answerable at every instant,
 * including those two — so A10 needs no window, no ratio, no tolerance and no hold.
 *
 * ## ⛔ IT SHARES A CONFIGURATION WITH RULE 6, AND NOW THEY PARTITION IT
 *
 * | the finger ON the object | the other finger | rule |
 * |---|---|---|
 * | **MOVING** | anything | **rule 6** — translate; the holder drives |
 * | **STATIONARY** | MOVING in y | ⭐ **A10** — translate in DEPTH; the anchor drives |
 * | STATIONARY | STATIONARY | nothing |
 *
 * ⛔ **THE HOLDER WINS EVERY TIE**, so the two rules cannot both fire. That is the
 * property A6 never had.
 *
 * ⭐ And the roles swap cleanly with the intent: the finger that is *doing something* is
 * the one that drives. Rule 6's anchor was always a mode selector that contributed no
 * motion; here it contributes the motion and the object's own finger becomes the selector.
 *
 * ## ⭐ THE GAIN IS RULE 6's, REDIRECTED
 *
 * The displacement uses `trackingMetresPerPx` — the same computed factor rule 6 uses — so
 * **one hand's-worth of finger travel moves the object the same distance whichever
 * direction it is going**, in the screen plane or into the scene. ⛔ Not a
 * metres-per-millimetre constant, which rule 6 proved cannot serve both ends of a 20× zoom
 * clamp. `gainTranslateDepth` multiplies it, and 1.0 means *as far as a drag would*.
 *
 * ⚠ It is NOT "the object stays under the finger": that mapping diverges as the camera
 * levels out, because an object pushed along the ground barely moves on screen when you are
 * looking at it horizontally. ⭐ Consistency with rule 6 is a property that holds at every
 * camera elevation; tracking is not.
 *
 * ⛔ ENGINE-FREE.
 */
import { CAMERA_NEAR_PLANE_M, type GestureConfig } from "./gestureConfig";
import type { MotionState } from "./motion";
import type { Assignment, Behaviour } from "./assignment";
import { pxToMm } from "../core/units";
import { add, dot, normalize, scale, sub, type Vec3 } from "../core/vec";

/**
 * How near and how far a depth translation may drive an object, in metres of HORIZONTAL
 * depth. ⭐ Carried unchanged from A5: the bounds were derived, not invented, and changing
 * the TRIGGER does not change where an object may end up.
 *
 * * **The floor is twice the near plane.** `pinch.ts` records why: a zoom across the near
 *   plane produces *a black page with no error at all*. An object pushed onto the camera
 *   would clip through and invert behind it — the same silent failure, one object at a
 *   time.
 * * **The ceiling is the camera's own maximum orbit radius.** Beyond it the object cannot
 *   be brought back into view even by zooming all the way out. ⚠ A gesture must not reach a
 *   state the user cannot undo.
 *
 * ⚠ Whether the ceiling ever BINDS is on the HUD rather than asserted here — the owner
 * looked for it and could not see it, and a claim a device cannot check is an assertion.
 */
export function depthLimits(cfg: GestureConfig): { minM: number; maxM: number } {
  return { minM: 2 * CAMERA_NEAR_PLANE_M, maxM: cfg.cameraRadiusMaxM };
}

/**
 * The direction depth runs along: the camera's view direction with its gravity component
 * removed, normalised. `null` when there is none.
 *
 * ⛔⛔ HORIZONTAL, NOT ALONG THE VIEW AXIS — the owner's correction, and the reason is that
 * **gravity is the primary constraint in this game**. §2 rule 2ter anchors a face to it and
 * parts are assembled on a working plane, so a camera looking down would make "away" point
 * into the FLOOR. A gesture meaning *"put this further away"* must not change an object's
 * HEIGHT.
 *
 * ⛔ It vanishes when the camera looks straight down, and the orbit surface's top ring is a
 * steep look-down. ⚠ The MECHANISM of the weakening is the camera's POSITION, not its
 * angle: flattening does not turn the view direction, so what shrinks is the horizontal
 * distance as the camera climbs overhead.
 */
export function depthPushDirection(viewAxis: Vec3, gravityDown: Vec3): Vec3 | null {
  const g = normalize(gravityDown);
  const v = normalize(viewAxis);
  if (!g || !v) return null;
  return normalize(sub(v, scale(g, dot(v, g))));
}

/**
 * ⭐⭐ **A10's GATE.** Is this hand asking for depth?
 *
 * @param holder the motion state of the touchpoint **on the object** — the one whose
 *   raycast hit it.
 * @param anchor the motion state of the touchpoint **outside every object**.
 *
 * ⛔⛔ THE HOLDER'S STILLNESS IS THE WHOLE DISCRIMINATOR, AND IT IS THE ONLY QUESTION
 * ASKED. A6 asked whether the two fingers were travelling *together*, which is a question
 * with **no answer** for a window at the start of every gesture and again at every
 * reversal, where both travels pass through zero and the ratio becomes jitter ÷ jitter.
 * ⭐ *"Is that finger still?"* is answerable at every instant, including those two.
 *
 * ⭐ It is also §1.1's own vocabulary: *"every 'delta position' in the spec means MOVING;
 * every 'no delta position' means STATIONARY."* ⛔ So the gate takes MOTION STATES, never
 * a speed or a delta of its own — a second definition of *moving* would be free to
 * disagree with the one every other rule uses.
 *
 * ⚠ **A hysteretic state is what makes this safe, and an instantaneous one would not be.**
 * A resting finger jitters over the measured 0.761 mm, and a finger can CREEP below any
 * speed threshold indefinitely. §1.1 answers both: `moveEnterDistance` is net displacement
 * from an anchor, and `moveExitDistance` bounds the excursion during settle candidacy. The
 * gate inherits both by reading the state rather than the samples.
 *
 * ⛔ THE HOLDER WINS EVERY TIE. If both fingers move, it is rule 6 — the object follows
 * the finger touching it. That is not a tie-break invented here; it is what makes the two
 * rules a partition instead of an overlap.
 */
export function depthGate(holder: MotionState, anchor: MotionState): DepthVerdict {
  return holder === "STATIONARY" && anchor === "MOVING" ? "DEPTH" : "IDLE";
}

/** What the gate decided. ⭐ Two states, because there is nothing to be undecided about. */
export type DepthVerdict = "DEPTH" | "IDLE";

/**
 * Move an object in horizontal depth by one frame's common travel.
 *
 * @param push     the horizontal direction depth runs along — `GravityFrame.depth`.
 * @param awaySign +1 when moving the object AWAY makes it rise on screen (the camera looks
 *   DOWN on the scene), −1 when it makes it sink (the camera looks UP from below).
 *   ⛔⛔ IT IS NOT A CONSTANT, AND ASSUMING IT WAS WAS A DEFECT FOUND BY FINGER: *"when the
 *   camera is on the bottom ring facing upwards, the depth translation is chaotic."* An
 *   object further off along the ground rises toward the horizon seen from above and SINKS
 *   seen from below, so *fingers-up means away* is right on the top rings and backwards on
 *   the bottom one — and a hand correcting a backwards control produces exactly the chaos
 *   that was reported. ⭐ `Math.sign(GravityFrame.towardGravity)` is the value.
 *   ⚠ **0 at a level camera**, where a depth change produces no screen motion and there is
 *   nothing to follow. The gesture goes quiet rather than guessing a direction.
 * @param commonDyPx this frame's shared vertical travel, CSS pixels. ⚠ Screen y grows
 *   DOWNWARD.
 * @param metresPerPx `trackingMetresPerPx` for the camera — rule 6's computed factor, so a
 *   given finger travel moves the object as far into the scene as it would across it.
 *
 * ⛔ Returns the position UNCHANGED when there is no push direction or the object is not in
 * front of the camera — never a `NaN`, which would never wash out of a placement.
 */
export function depthTranslate(
  cameraPosition: Vec3,
  objectPosition: Vec3,
  push: Vec3,
  awaySign: number,
  commonDyPx: number,
  metresPerPx: number,
  gain: number,
  minM: number,
  maxM: number,
): Vec3 {
  const dir = normalize(push);
  if (!dir || !Number.isFinite(commonDyPx) || !Number.isFinite(metresPerPx)) {
    return objectPosition;
  }
  // ⛔ A level camera shows nothing for a depth change, so there is no direction to
  // follow. Suppress rather than pick one — `LESSONS_CARRIED` §6.
  const sign = Math.sign(awaySign);
  if (sign === 0 || !Number.isFinite(awaySign)) return objectPosition;

  const depth = dot(sub(objectPosition, cameraPosition), dir);
  if (!(depth > 0)) return objectPosition;

  // ⚠ NEGATED because screen y grows downward; ⭐ times `sign` because which way "away"
  // looks depends on whether the camera is above the scene or below it.
  const wanted = depth - commonDyPx * metresPerPx * gain * sign;
  const clamped = Math.min(maxM, Math.max(minM, wanted));
  // ⭐ Only the along-push component moves, so HEIGHT is untouched by construction.
  return add(objectPosition, scale(dir, clamped - depth));
}

/**
 * ⭐⭐⭐ **AMENDMENT A12** — what the SECOND touchpoint is asking for, per axis.
 *
 * > *"One touchpoint idle on object && second touchpoint inside or outside any object &&
 * > delta position y → depth translation control. …&& delta position x → roll rotation
 * > control. This will remove the conflict and decision lag between yaw/pitch and roll and
 * > the jump on roll."*
 *
 * ⭐⭐ THE AMBIGUITY IS DISSOLVED BY MOVING THE GESTURE, NOT BY DECIDING BETTER. Yaw/pitch
 * is ONE touchpoint; roll is TWO. They stopped being the same hand shape, so nothing has to
 * tell them apart — and everything that existed to do so is gone: the circle fit, the
 * `rollAngle` commit threshold, the provisional yaw/pitch, A8's rebase, and **the jump**.
 *
 * ⭐ It composes with A11's per-axis deadband exactly. The second finger's x and y break
 * out of their bands INDEPENDENTLY, so a mostly-horizontal drag is pure roll and a
 * mostly-vertical one is pure depth. ⛔ With one shared MOVING flag — or a radial band —
 * every diagonal would do both, and the object would creep away while you rolled it.
 *
 * ⛔ THE HOLDER WINS EVERY TIE, as in A10: while the finger on the object is moving this
 * returns nothing at all, because that is rule 6.
 *
 * ⛔ It DECIDES; it does not scale. A gate that also applied a gain would be a second gain,
 * free to disagree with the one in the config.
 */
export function secondFingerDrive(
  holder: MotionState,
  secondAxes: { readonly x: MotionState; readonly y: MotionState },
  secondStep: { readonly dx: number; readonly dy: number },
): { readonly rollDxPx: number; readonly depthDyPx: number } {
  // ⭐ The SAME gate as A10, asked once per axis — which is all A12 adds to it.
  return {
    rollDxPx: depthGate(holder, secondAxes.x) === "DEPTH" ? secondStep.dx : 0,
    depthDyPx: depthGate(holder, secondAxes.y) === "DEPTH" ? secondStep.dy : 0,
  };
}

/**
 * ⭐ A12's roll: DEGREES from the second touchpoint's horizontal travel.
 *
 * @param dxPx      deadbanded horizontal travel, CSS pixels.
 * @param degPerMm  `gainRollDrag` — degrees of roll per MILLIMETRE of travel.
 *
 * ⛔ MILLIMETRES, rule 3: a degrees-per-PIXEL gain would roll a phone and a tablet by
 * different amounts for the same hand movement.
 *
 * ⭐⭐ AND IT IS AN INCREMENT, not an absolute angle against a baseline. ⚠ The old
 * 2quinte roll was a swept angle measured from a baseline, and that baseline going stale is
 * precisely what produced the jump at the commit — `lastRollDeg` tracked the uncommitted
 * phase, so ~60° was dropped at the moment the pose was rebased. An increment has no
 * baseline to lose.
 */
export function rollDragDeg(dxPx: number, degPerMm: number): number {
  return pxToMm(dxPx) * degPerMm;
}

/**
 * ⭐⭐⭐ **AMENDMENT A13** — what the finger ON THE OBJECT is doing, when it moves.
 *
 * > *"One touchpoint on object && delta position x or y → horizontal x or gravity axis
 * > translation. One touchpoint on object with delta position x or y && second touchpoint
 * > idle anywhere → rotation on yaw along gravity axis or pitch along horizontal x axis."*
 *
 * ⭐⭐ **A SECOND TOUCHPOINT BEING DOWN IS THE WHOLE INPUT.** It contributes no motion; its
 * presence turns the holder's drag from a translation into a rotation.
 *
 * |               | second absent | second DOWN |
 * |---|---|---|
 * | **holder MOVING** | translate | ⭐ **ROTATE** |
 * | **holder IDLE**   | — | x → roll, y → depth |
 *
 * ## ⛔⛔⛔ IT READS PRESENCE **ALONE**, AND THE DEVICE SAID SO TWICE
 *
 * ⚠ The owner's rules do not name the cell where BOTH fingers move. I first decided it as
 * `TRANSLATE` — *the holder wins every tie* — and a hand overturned it:
 *
 * > *"If I transition quickly there is a translation then a rotation, if I transition
 * > slowly there is directly a rotation."*
 *
 * ⭐⭐ **THE TIMING SIGNATURE IS THE WHOLE DIAGNOSIS.** A finger PLACED QUICKLY skids as it
 * lands — the reported centroid slides while the contact area grows — so it reads `MOVING`
 * for as long as the landing takes, and the mode followed it. Placed SLOWLY it never leaves
 * its band, so the mode was right at once. ⛔ Nothing about the *gesture* differed; only the
 * landing did, and a mode must not depend on how briskly a finger arrives.
 *
 * ⛔⛔ **`IN4` RECORDED THIS VERDICT ALREADY, ON 2026-09-14**, when a mode keyed on the
 * anchor's `STATIONARY` state was overturned by a hand first try. The lesson written then is
 * the one that applies now:
 *
 * > *`MOVING`/`STATIONARY` is a NOISY, CONTINUOUS reading … whether a finger is DOWN is
 * > neither: it is discrete and deliberate, it changes only when a person decides it does,
 * > and it is the one thing they can see.*
 *
 * ⭐ So the motion state is used where it belongs — deciding what the second finger's own
 * travel DRIVES, once the holder is still (`secondFingerDrive`) — and never for choosing a
 * mode. ⚠ Two rules, two signals: **presence** picks the mode; **motion** supplies the
 * motion.
 *
 * ⛔⛔ **IT TAKES NO MOTION STATE, AND IT MUST NOT BE GIVEN ONE.** An earlier version
 * accepted one “so callers need not special-case it” and ignored it. ⚠ A dead parameter
 * named after the very signal a hand rejected **twice** is an invitation to wire it back,
 * and the signature is the cheapest place to make that impossible. ⭐ The motion state has a
 * job — `secondFingerDrive`, deciding what a moving second finger DRIVES — and this is not
 * it.
 *
 * ⭐⭐⭐ **AND THIS IS THE WHOLE OF THE `1.0.5` A/B** — the one inversion that separates the
 * two forks the owner intends to judge holistically. `ONE_FINGER_TRANSLATE` is `A13`, the
 * reading a hand has approved; `TWO_FINGER_TRANSLATE` is the **spec's original** assignment.
 * ⛔ Everything else in the input layer is assignment-agnostic, which is why this is a flag
 * and not a fork. See `input/assignment.ts`, and `adoptAssignment` for the latch rule:
 * **it may change only while nothing is touching the glass.**
 *
 * @param secondPresent whether a second touchpoint is down, counting `A14`'s replacement
 *   grace.
 * @param assignment which reading of §2/§4 is in force. ⛔ REQUIRED, and deliberately not
 *   defaulted: a default would let a call site silently get fork A while the owner was
 *   testing fork B, and *which rule table am I in* is the one thing an A/B must never guess.
 */
export function holderDrive(
  secondPresent: boolean,
  assignment: Assignment,
): "TRANSLATE" | "ROTATE" {
  if (assignment === "TWO_FINGER_TRANSLATE") {
    // ⭐ The spec as written: §2 rule 2bis on one touchpoint, §4 rule 6 on two.
    return secondPresent ? "TRANSLATE" : "ROTATE";
  }
  // ⭐ `A13`/`D23`: the commonest gesture on the easiest hand shape.
  return secondPresent ? "ROTATE" : "TRANSLATE";
}

/**
 * ⭐⭐⭐ **AMENDMENT A14** — is a second touchpoint holding, counting a replacement in
 * progress?
 *
 * > *"…second touchpoint is released then pressed on screen outside any object and I
 * > IMMEDIATELY input delta position the first touchpoint → first object continues to
 * > translate for a while then rotates."*
 *
 * ⛔⛔ THE MODE LOGIC WAS NEVER WRONG. Between the lift and the press there is genuinely
 * **one touchpoint down**, and `A13` says one touchpoint TRANSLATES. So the object
 * translates for exactly as long as the swap takes — and a lift and a replace is 150–300 ms
 * of hand, which is very visible.
 *
 * ⭐⭐ THAT IS ALSO WHY THE OWNER'S THREE CASES DIFFER *ONLY BY TIMING*:
 *
 * | case | during the swap | what is seen |
 * |---|---|---|
 * | 1 — no lift at all | no interval | correct |
 * | 2 — holder WAITS | interval exists, holder still | nothing to see |
 * | 3 — holder KEEPS MOVING | interval exists, holder moving | ⛔ it translates |
 *
 * ⭐⭐⭐ SO THE RULE IS RIGHT AND THE GESTURE MODEL WAS WRONG: **a lift-and-replace is ONE
 * intention**, and dropping to one-touchpoint behaviour in the middle of it is the artefact.
 *
 * ⛔ THE GRACE IS KEYED ON A **LIFT** — discrete, deliberate and visible — never on a motion
 * state. That is the rule the previous round of this defect cost us, and it is honoured
 * here rather than quietly re-broken.
 *
 * ⚠ **THE COST, STATED**: returning to one-touchpoint translation is delayed by the grace.
 * That is a real delay on a deliberate act, and it is the trade. ⭐ A grace of `0` restores
 * the old behaviour exactly, so the slider can turn it off.
 *
 * @param present      whether a second touchpoint is down right now.
 * @param msSinceLift  milliseconds since the last second-touchpoint LIFT, or `null` if none
 *   has ever happened — which is not the same as a lift infinitely long ago.
 */
export function secondTouchHeld(
  present: boolean,
  msSinceLift: number | null,
  graceMs: number,
): boolean {
  if (present) return true;
  return msSinceLift !== null && msSinceLift < graceMs;
}

/**
 * ⭐⭐⭐ **THE ONE PLACE A HELD OBJECT'S MODE IS DECIDED**, across all three forks.
 *
 * ⛔ It exists so the fork branch is NOT in `scene.ts`. `D23` recorded what that costs:
 * *"the WIRING has no vector — breaking the mode selection in `scene.ts` reddens nothing."*
 * ⭐ Here it reddens something, for every fork, including the cell each fork disagrees on.
 *
 * | fork | what decides the mode |
 * |---|---|
 * | A `ONE_FINGER_TRANSLATE` | **presence**: a second touchpoint means rotate |
 * | B `TWO_FINGER_TRANSLATE` | **presence**, inverted: a second touchpoint means translate |
 * | C `TAP_TOGGLE` | ⛔ **neither** — a discrete TAP flips it, and presence is ignored here |
 *
 * ⚠ Fork C ignoring `secondPresent` IS the whole of fork C: a held second finger keeps only
 * the meanings it already has (depth while the holder is still, roll on its x), and what the
 * holder's own drag DOES becomes a per-gesture toggle instead.
 *
 * @param toggled fork C's per-gesture behaviour. ⛔ Required, and unused by A and B — a
 *   caller that cannot supply it has no business choosing a mode, and defaulting it would
 *   let fork C silently run fork A's answer.
 */
export function modeFor(
  assignment: Assignment,
  secondPresent: boolean,
  toggled: Behaviour,
): "TRANSLATE" | "ROTATE" {
  if (assignment === "TAP_TOGGLE") return toggled;
  return holderDrive(secondPresent, assignment);
}
