/**
 * ⛔⛔ **WHAT THIS FILE HOLDS NOW**: `depthLimits` (the derived depth bounds), `secondFingerDrive`
 * (which axis a second finger drives when the mode picks) and `rollDragDeg`. ⛔ The A10 depth rule
 * described below — `depthTranslate` and its still-holder gate — is DELETED (the gate by `D43`, the
 * function by `D109`); the second touch now drives the body's GRAVITY axis through
 * `axis_translate.ts`. The header is kept as the history of why.
 *
 * AMENDMENT **A10** — **DEPTH TRANSLATION BY A STILL HOLDER AND A MOVING ANCHOR.**
 *
 * Design of record: `Claude/10_INPUT_TOUCH/AMENDMENTS_R5.md` A10, superseding A6's
 * trigger. A5's GEOMETRY is untouched by both: depth is horizontal, and height never
 * changes.
 *
 * > The touchpoint **on the object is still**, and the touchpoint **outside it has a delta
 * > position in y** — the object translates in horizontal depth, by that anchor's travel.
 *
 * ## ⛔⛔ WHY A6 HAD TO GO, AND IT WAS FOUND BY FINGER
 *
 * A6 asked whether both fingers were travelling in y **together**, within a ratio, over a
 * window. ⚠ The owner: *"I don't like the conflict generated by the control of depth
 * translation by two fingers."*
 *
 * ⭐⭐ **THE FAULT WAS IN THE QUESTION, NOT IN THE ANSWER.** *"Are these two travels
 * equal?"* has **no answer** at two moments that occur in every single gesture:
 *
 * * **at a reversal**, both travels pass through zero — the ratio is jitter ÷ jitter;
 * * **at the start**, one finger has not moved yet — which is exactly rule 6's shape.
 *
 * A6 answered both by WAITING (two windows) and by WITHHOLDING rule 6's vertical
 * meanwhile, so the first window of travel was discarded and the hand felt a hesitation at
 * each end of every drag. ⛔ *"Is that finger still?"* is answerable at every instant,
 * including those two — so A10 needs no window, no ratio, no tolerance and no hold.
 *
 * ## ⛔ IT SHARES A CONFIGURATION WITH RULE 6, AND NOW THEY PARTITION IT
 *
 * | the finger ON the object | the other finger | rule |
 * |---|---|---|
 * | **MOVING** | anything | **rule 6** — translate; the holder drives |
 * | **STATIONARY** | MOVING in y | ⭐ **A10** — translate in DEPTH; the anchor drives |
 * | STATIONARY | STATIONARY | nothing |
 *
 * ⛔ **THE HOLDER WINS EVERY TIE**, so the two rules cannot both fire. That is the
 * property A6 never had.
 *
 * ⭐ And the roles swap cleanly with the intent: the finger that is *doing something* is
 * the one that drives. Rule 6's anchor was always a mode selector that contributed no
 * motion; here it contributes the motion and the object's own finger becomes the selector.
 *
 * ## ⭐ THE GAIN IS RULE 6's, REDIRECTED
 *
 * The displacement uses `trackingMetresPerPx` — the same computed factor rule 6 uses — so
 * **one hand's-worth of finger travel moves the object the same distance whichever
 * direction it is going**, in the screen plane or into the scene. ⛔ Not a
 * metres-per-millimetre constant, which rule 6 proved cannot serve both ends of a 20× zoom
 * clamp. `gainTranslateDepth` multiplies it, and 1.0 means *as far as a drag would*.
 *
 * ⚠ It is NOT "the object stays under the finger": that mapping diverges as the camera
 * levels out, because an object pushed along the ground barely moves on screen when you are
 * looking at it horizontally. ⭐ Consistency with rule 6 is a property that holds at every
 * camera elevation; tracking is not.
 *
 * ⛔ ENGINE-FREE.
 */
import { CAMERA_NEAR_PLANE_M, type GestureConfig } from "./gestureConfig";
import type { MotionState } from "./motion";
import type { Behaviour } from "./mode_toggle";
import { pxToMm } from "../core/units";

/**
 * How near and how far a depth translation may drive an object, in metres of HORIZONTAL
 * depth. ⭐ Carried unchanged from A5: the bounds were derived, not invented, and changing
 * the TRIGGER does not change where an object may end up.
 *
 * * **The floor is twice the near plane.** `pinch.ts` records why: a zoom across the near
 *   plane produces *a black page with no error at all*. An object pushed onto the camera
 *   would clip through and invert behind it — the same silent failure, one object at a
 *   time.
 * * **The ceiling is the camera's own maximum orbit radius.** Beyond it the object cannot
 *   be brought back into view even by zooming all the way out. ⚠ A gesture must not reach a
 *   state the user cannot undo.
 *
 * ⚠ Whether the ceiling ever BINDS is on the HUD rather than asserted here — the owner
 * looked for it and could not see it, and a claim a device cannot check is an assertion.
 *
 * ⛔⛔ **`D195` (2026-10-01): A LEVEL WITH A PLAY VOLUME HAS NO CEILING.** *"I am trying to push the piece 1 … the
 * pieces do not translate further"* — the HUD read `depth=3.00m ⛔MAX`: a piece behind the painting was 3 m from a camera
 * zoomed out (or, on the double-orbit prototype, held 1.5 m behind its box), so a push AWAY was refused in the middle of the
 * floor. ⭐ The ceiling's reason — *a body the user cannot bring back* — is answered by `D181`'s play volume, which keeps
 * every piece on the floor the camera orbits. The floor (the near plane) stays everywhere; a scene with no volume
 * (`Scene_0`) keeps the ceiling.
 */
export function depthLimits(cfg: GestureConfig, hasPlayVolume = false): { minM: number; maxM: number } {
  return { minM: 2 * CAMERA_NEAR_PLANE_M, maxM: hasPlayVolume ? Infinity : cfg.cameraRadiusMaxM };
}


// ⛔⛔⛔ **`A10`'s DEPTH GATE WAS DELETED HERE — 2026-09-17, ON A DEVICE REPORT.**
//
// > *"When the second touchpoint provides input for depth or roll, it does not integrate
// > simultaneously with the x and y inputs of the first touchpoint (each touchpoint have to
// > wait that the other idle for its input to get integrated). I want everything
// > simultaneous."*
//
// ⭐ What stood here was `depthGate(holder, anchor)`, which returned `DEPTH` only while the
// finger ON the object was `STATIONARY`. ⛔⛔ That was not an accident and not a bug: it made
// rule 6 and depth a **partition** of the two-finger configuration rather than an overlap,
// and it replaced `A6`'s unanswerable question (*are these two travels equal?*) with one that
// has an answer at every instant (*is that finger still?*). Six models and five device passes
// are behind it — `queue_notes/IN8.md`.
//
// ⚠⚠ **THE OWNER HAS NOW REJECTED THE PARTITION ITSELF**, which is a different thing from
// rejecting its implementation. The new reading is simpler: **each finger owns its own
// channel** — the holder's x/y, the second finger's single axis — and they SUM, exactly as the
// holder's own x and y already sum. ⭐ Nothing is left to discriminate, so there is no gate: a
// question that does not have to be asked cannot be asked wrongly.
// ⛔ What is lost with it, stated: a hand can no longer move one finger and be certain only
// one rule ran. That was the partition's whole value, and it is the owner's to trade away.

/**
 * ⭐⭐⭐ **AMENDMENT A12** — what the SECOND touchpoint is asking for, per axis.
 *
 * > *"One touchpoint idle on object && second touchpoint inside or outside any object &&
 * > delta position y → depth translation control. …&& delta position x → roll rotation
 * > control. This will remove the conflict and decision lag between yaw/pitch and roll and
 * > the jump on roll."*
 *
 * ⭐⭐ THE AMBIGUITY IS DISSOLVED BY MOVING THE GESTURE, NOT BY DECIDING BETTER. Yaw/pitch
 * is ONE touchpoint; roll is TWO. They stopped being the same hand shape, so nothing has to
 * tell them apart — and everything that existed to do so is gone: the circle fit, the
 * `rollAngle` commit threshold, the provisional yaw/pitch, A8's rebase, and **the jump**.
 *
 * ⭐ It composes with A11's per-axis deadband exactly. The second finger's x and y break
 * out of their bands INDEPENDENTLY, so a mostly-horizontal drag is pure roll and a
 * mostly-vertical one is pure depth. ⛔ With one shared MOVING flag — or a radial band —
 * every diagonal would do both, and the object would creep away while you rolled it.
 *
 * ✅ **BOTH FINGERS DRIVE AT ONCE SINCE 2026-09-17** (owner: *"I want everything
 * simultaneous"*). ⛔ The holder's stillness is not consulted: its x/y run rule 6 (or 2bis)
 * while this axis runs depth (or roll), and the two SUM — exactly as the holder's own x and y
 * already sum. ⚠ The old *"holder wins every tie"* partition is gone with `A10`'s gate.
 *
 * ⛔ It DECIDES; it does not scale. A gate that also applied a gain would be a second gain,
 * free to disagree with the one in the config.
 */
export function secondFingerDrive(
  secondAxes: { readonly x: MotionState; readonly y: MotionState },
  secondStep: { readonly dx: number; readonly dy: number },
  toggled: Behaviour,
): { readonly rollDxPx: number; readonly depthDyPx: number } {
  // ⭐⭐ ONE QUESTION PER AXIS, AND IT IS ONLY ABOUT THIS FINGER: *is this axis moving?*
  // ⛔ The holder is not consulted at all since 2026-09-17 — see the note where `A10`'s gate
  // used to be. ⚠ `MOVING` is §1.1's hysteretic state, never a speed of our own: a second
  // definition of *moving* would be free to disagree with the one every other rule uses.
  const gate = (axis: MotionState): boolean => axis === "MOVING";
  // ⛔⛔ ONE AXIS, NEVER BOTH, AND THE MODE PICKS IT (`A16`): *"depending on which is
  // toggled, the second touchpoint shall only control depth translation by delta position y
  // or roll by delta position x (not both). Switching between the two shall indeed require
  // the tap."*
  // ⭐⭐ THE PAIRING IS BY KIND, which is what makes one toggle enough for two fingers:
  // `TRANSLATE` pairs the holder's screen-plane drag with the second finger's **depth** —
  // both translations — and `ROTATE` pairs yaw/pitch with **roll**. One question, *am I
  // translating or rotating?*, and both fingers follow the same answer.
  // ⚠⚠ `A12`'s TWO-AXES-AT-ONCE CAME BACK — for an aligned Follower (`D59`/`D108`) and a free body
  // in `TRANSLATE` (`D123`), through `bothAxesSecondDrive`. ⭐ So this one-axis pick is reached
  // only by a free body in `ROTATE` (`secondTouchDrive` → `MODE_PICKS`); the `TRANSLATE` branch
  // below is kept for completeness.
  if (toggled === "ROTATE") {
    return { rollDxPx: gate(secondAxes.x) ? secondStep.dx : 0, depthDyPx: 0 };
  }
  return { rollDxPx: 0, depthDyPx: gate(secondAxes.y) ? secondStep.dy : 0 };
}

/**
 * ⭐ A12's roll: DEGREES from the second touchpoint's horizontal travel.
 *
 * @param dxPx      deadbanded horizontal travel, CSS pixels.
 * @param degPerMm  `gainRollDrag` — degrees of roll per MILLIMETRE of travel.
 *
 * ⛔ MILLIMETRES, rule 3: a degrees-per-PIXEL gain would roll a phone and a tablet by
 * different amounts for the same hand movement.
 *
 * ⭐⭐ AND IT IS AN INCREMENT, not an absolute angle against a baseline. ⚠ The old
 * 2quinte roll was a swept angle measured from a baseline, and that baseline going stale is
 * precisely what produced the jump at the commit — `lastRollDeg` tracked the uncommitted
 * phase, so ~60° was dropped at the moment the pose was rebased. An increment has no
 * baseline to lose.
 */
export function rollDragDeg(dxPx: number, degPerMm: number): number {
  return pxToMm(dxPx) * degPerMm;
}



